### ISSUE TITLE
using it

### ISSUE THREAD

**Issue by ubuntunewdev100** [jfix/npm-random-file#2]
Hi, i was wondering what else can we use it for? I manage to get a random file name with console.log, but i cant pass the result to a variable and use it further in my script. 

i.e. 

const dir = '/test/'
var response = randomFile(dir, (err, file) => {
  
  
     
     return file
  
  
})
console.log(response);

1. Expected output: the name of the file
2. Actual output: undefined.

**Comment by jfix** [comment]
Well, you would replace the sample `console.log(response);` line with something that's actually useful for you. Not sure this answers your question.

Maybe your issue is rather with the fact that the programming style is callback-based. Your code should continue inside the function, i.e. where you currently have `return file`. Please have a look online for how this works in JavaScript.

> Note that this library could probably be rewritten to also support Promises-style coding or async/await.
